---
title: "Preliminary Analyses RRI Tool Kit"
author: "Juan C. Correa"
output:
  word_document: default
---

# Intro
This is a short preliminary analysis of the contents included in the sample of projects indexed by the *Responsible Research and Innovation* (RRI) toolkit. By employing web scraping techniques, we were able to retrieve a total of 1,414 documents from RRI, along with a brief document description, their titles, and the discipline they belong to. 

```{r, echo=FALSE}
setwd("~/Documents/PaperOtoFelipe/")
library(readxl)
LT <- read_excel("RawDataRRI.xlsx", sheet = "Raw LowerTags")
library(tidyr)
disciplines <- LT[1:47]
```


As the initial data base contained several disciplines with quite similar categories (e.g., agrobiotechnology, agriculture, plant biology, smart farming), we decided to merge these categories under a single name. The resulting merged categories were re-named as follows:

* Agro = agribiotechnology + agriculture + plant biology + smart farming + Food + Food, agriculture, forestry, water and bio-economy + plant biology + rural environment
* Climate = climate action + climate adaptation strategies + climate crisis + Climate, environment, and resources
* Energy = Energy + energy transition + renewable energy
* Ethics = ai ethics + Ethics + ethics of ai + responsible technology + security
* Health = health care + health technology + Health, demography & wellbeing + patient engagement + vaccine hesitancy + vaccines
* Technologies = Artificial intelligence + Digital technologies + emerging technologies + robotics
* Education = Education Community + Science education
* Govern = Governance + policy design + public engagement
